#!/usr/bin/bash
#
# Installation scripts for ubos-admin package.
#
# Copyright (C) 2014 and later, Indie Computing Corp. All rights reserved. License: see package.
#

## arg 1: the old package version
pre_remove() {
    cat <<MSG;

Hey hacker,

Sorry to see you go.
Hope to see you again in the future.

Regards,
    Indie Computing   indiecomputing.com
    UBOS              ubos.net

MSG
}

##
pre_install() {
    ensureChattr

    # Fix file leftover from package js52
    [[ -e /usr/lib/libmozjs-52.so.0 ]] && ! pacman -Qo /usr/lib/libmozjs-52.so.0 > /dev/null 2>&1 && rm -f /usr/lib/libmozjs-52.so.0
}

post_install() {
    perl -MUBOS::Host -e 'UBOS::Host::ensureSnapperConfig();'
}

pre_upgrade() {
    # Fix file leftover from package js52
    [[ -e /usr/lib/libmozjs-52.so.0 ]] && ! pacman -Qo /usr/lib/libmozjs-52.so.0 > /dev/null 2>&1 && rm -f /usr/lib/libmozjs-52.so.0

    # Services were renamed
    systemctl stop    ubos-httpd.service > /dev/null 2>&1 || true
    systemctl disable ubos-httpd.service > /dev/null 2>&1 || true

    systemctl stop    ubos-mysqld.service > /dev/null 2>&1 || true
    systemctl disable ubos-mysqld.service > /dev/null 2>&1 || true
}

## arg 1: the new package version
## arg 2: the old package version
post_upgrade() {
    ensureChattr

    # Make Java 8 the default
    if [ -e /usr/lib/jvm/default ]; then
        rm /usr/lib/jvm/default
    fi
    if [ -e /usr/lib/jvm/default-runtime ]; then
        rm /usr/lib/jvm/default-runtime
    fi
    if [ ! -d /usr/lib/jvm ]; then
        mkdir -m755 /usr/lib/jvm
    fi
    ln -sf java-8-openjdk/jre /usr/lib/jvm/default
    ln -sf java-8-openjdk/jre /usr/lib/jvm/default-runtime

    systemctl daemon-reload

    perl -MUBOS::Host -e 'UBOS::Host::ensureSnapperConfig();'

    systemctl enable ubos-ready.service snapper-timeline.timer snapper-cleanup.timer
    systemctl start  ubos-ready.service snapper-timeline.timer snapper-cleanup.timer

    # fix old device classes -- works for both rpi and rpi2
    perl -pi -e 's/UBOS_DEVICECLASS="raspberry-pi/UBOS_DEVICECLASS="rpi/' /etc/os-release

    if [ -x /usr/share/ubos-admin/bin/post-upgrade ]; then /usr/share/ubos-admin/bin/post-upgrade; fi
}

ensureChattr() {
    ( [ -d /var/log/journal ] || mkdir /var/log/journal ) && chattr +C /var/log/journal
}
