#!/usr/bin/bash
#
# Installation scripts for ubos-admin package.
#
# This file is part of ubos-admin.
# (C) 2012-2014 Indie Computing Corp.
#
# ubos-admin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ubos-admin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ubos-admin.  If not, see <http://www.gnu.org/licenses/>.
#

## arg 1: the old package version
pre_remove() {
    cat <<MSG;

Hey hacker,

Sorry to see you go.
Hope to see you again in the future.

Regards,
    Indie Computing   indiecomputing.com
    UBOS              ubos.net

MSG
}

## arg 1: the new package version
## arg 2: the old package version
post_upgrade() {
    systemctl daemon-reload
}
