#!/usr/bin/perl
#
# Installation scripts for indiebox-admin package. Just bridge to Perl.
#
# This file is part of indiebox-admin.
# (C) 2012-2014 Indie Computing Corp.
#
# indiebox-admin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# indiebox-admin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with indiebox-admin.  If not, see <http://www.gnu.org/licenses/>.
#

## arg 1:  the new package version
pre_install() {
    # not used
    true
}

## arg 1:  the new package version
post_install() {
    perl -MIndieBox::Installer -e "IndieBox::Installer::post_install( '$1' )"
}

## arg 1:  the new package version
## arg 2:  the old package version
pre_upgrade() {
    # not used
    true
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
    perl -MIndieBox::Installer -e "IndieBox::Installer::post_upgrade( '$1', '$2' )"
}

## arg 1:  the old package version
pre_remove() {
    perl -MIndieBox::Installer -e "IndieBox::Installer::pre_remove( '$1' )"
}

## arg 1:  the old package version
post_remove() {
    # not used
    true
}
